# Generated by Django 5.2.5 on 2025-09-29 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=255, verbose_name="Место")),
                (
                    "time_success",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Время на выполнение привычки в секундах",
                        verbose_name="Время выполнения (сек)",
                    ),
                ),
                ("action", models.CharField(max_length=500, verbose_name="Действие")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                (
                    "period",
                    models.PositiveIntegerField(
                        choices=[(1, "Ежедневно"), (7, "Еженедельно"), (30, "Ежемесячно")],
                        default=1,
                        help_text="Периодичность выполнения привычки",
                        verbose_name="Частота выполнения привычки",
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=500, null=True, verbose_name="Вознаграждение")),
                (
                    "max_time_processing",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Максимальное время на выполнение в секундах",
                        verbose_name="Максимальное время выполнения (сек)",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Признак публичности")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_habits",
                        to="habits.habits",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-created_at"],
            },
        ),
    ]
